# Generated by Django 5.0.2 on 2024-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
