# Generated by Django 5.0.1 on 2024-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0002_alter_supplier_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
