# Generated by Django 5.0.1 on 2024-04-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0003_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
